version: '3'
services:
    mysql:
        image: mysql:8.0
        container_name: mysqldb
        environment:            
            - MYSQL_PORT=3306
            - MYSQL_USER=admin
            - MYSQL_DATABASE=agenda_dev_db
            - MYSQL_PASSWORD=vUVzVaOCEnLubsarhgMc            
            - MYSQL_HOST=agenda-dev.coqndsdvmjhd.us-east-1.rds.amazonaws.com
        networks:
            - "my-network"
    dotnet:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: agendapp/dotnet
        container_name: dotnet
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "8888:80"
            - "8889:443"
        networks:
            - "my-network"
        depends_on:
            - "mysql"
    
networks: 
    my-network:
        driver: bridge